[build]
target="x86_64-os_dev.json"

[target.'cfg(target_os = "none")']
runner="bootimage runner"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]